language: objective-c
osx_image: xcode7.2
xcode_workspace: APJSONMapping.xcworkspace
xcode_scheme: APJSONMapping
script:
  - xcodebuild -workspace APJSONMapping.xcworkspace -scheme APJSONMapping -sdk macosx10.11 build test GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
