language: objective-c
osx_image: xcode6.4
script:
  - xctool -workspace APJSONMapping.xcworkspace -scheme APJSONMapping -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace APJSONMapping.xcworkspace -scheme APJSONMapping -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
