language: objective-c
osx_image: xcode6.4
script:
  - xctool -workspace NSObject+APJSONMapping.xcworkspace -scheme APJSONMapping -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace NSObject+APJSONMapping.xcworkspace -scheme APJSONMapping -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
