language: objective-c
script:
  - xctool -workspace NSObject+APJSONMapping.xcworkspace -scheme APJSONMapping -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace NSObject+APJSONMapping.xcworkspace -scheme APJSONMappingTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
