language: objective-c
script:
  - xctool -workspace NSObject+APJSONMapping.xcworkspace -scheme APJSONMapping -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace NSObject+APJSONMapping.xcworkspace -scheme APJSONMapping -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
